transcode-frontend:
  image: amsatique/transcode-frontend:latest
  labels:
    io.rancher.container.hostname_override: container_name
  restart: always
  volumes:
    - /data:/data
  links:
    - backend:backend
  environment:
    PUSHBULLET_API: ${pushbullet_api}
  tty: true
  expose:
    - 80
  command:
    - npm
    - start
transcode-backend:
  image: amsatique/transcode-backend:latest
  labels:
    io.rancher.container.hostname_override: container_name
  restart: always
  environment:
    MONGODB_NAME : ${mongodb_name}
    MONGODB_USER : ${mongodb_user}
    MONGODB_PASS : ${mongodb_pass}
    PRIVATE_KEY : ${private_key}
    EMAIL : ${email}
    EMAIL_NAME : ${email_name}
    EMAIL_PASSWD : ${email_passwd}
    MONGO_HOST : ${mongo_host}
    PUSHBULLET_API : ${pushbullet_api}
  tty: true
  links:
    - bdd:bdd
  volumes:
    - /data:/data
  command:
  - npm
  - start
transcode-bdd:
  image: amsatique/transcode-bdd:latest
  labels:
    io.rancher.container.hostname_override: container_name
  restart: always
  environment:
      MONGODB_PASS: ${mongodb_pass}
      PUSHBULLET_API: ${pushbullet_api}
  tty: true
  command: mongod
  volumes:
    - /data:/data
